### ISSUE TITLE
Exception handling error when starting experiment

### ISSUE THREAD

**Issue by aaravrav142** [davidbsp/patrolling_sim#3]
Hi,

I am using ROS Hydro on ubuntu 12.04. I was using this package earlier without any trouble. I recently upgraded it to the newest version. Did catkin_make and ran the start_experiment script, but getting this error : 

rd@robotics:~/catkin_ws/src/patrolling_sim$ ./start_experiment.py 
Unhandled exception in thread started by <function run_experiment at 0x1323500>
TypeError: run_experiment() takes exactly 12 arguments (11 given)

Can you help me with this???

Thanks 

Alex

**Comment by iocchi** [comment]
Dear Alex,
thanks for spotting this issue. I added a parameter for selecting different initial positions when starting an experiment, but I did not update one line in the script. Now it is fixed.

Best regards.
