### ISSUE TITLE
Issues with robot collisions and invalid TF frames with ROS navigation stack

### ISSUE THREAD

**Issue by jward0** [davidbsp/patrolling_sim#6]
I am running the simulator in ROS Noetic on Ubuntu 20.04.

When running in ROS navigation mode, I encountered this warning and error constantly displaying for all robots:
`[ERROR] [1652286776.128019954, 24.300000000]: TF Exception that should never happen for sensor frame: robot_0/base_laser_link, cloud frame: /robot_0/base_laser_link, Invalid argument "/robot_0/base_laser_link" passed to lookupTransform argument source_frame in tf2 frame_ids cannot start with a '/' like: 
Warning: Invalid argument "/robot_0/base_laser_link" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like: 
         at line 134 in /tmp/binarydeb/ros-noetic-tf2-0.7.5/src/buffer_core.cpp`
Tracing this through move_base showed it must have come from a callback in the ObstacleLayer class. I also saw that when starting robots, the following warning displayed:
`[ WARN] [1652286665.985781620, 15.500000000]: global_costmap: Parameter "plugins" not provided, loading pre-Hydro parameters
`
By modifying the param files for the costmaps I think I was able to solve both of these (the previously mentioned warnings and error disappeared at least)- I'm not sure exactly what was going on here but it appears that the pre-Hydro parameters being loaded was causing the attempt to use a TF frame starting with '/' during obstacle detection, which would also explain the constant robot collisions I was getting. Any thoughts on this issue would be appreciated.

However, this did not totally solve the main problem I was having with the simulator- when running in ROS navigation mode, robots were constantly crashing into walls and each other, and failing to recover. The change mentioned above significantly improved this, but did not solve it completely, and I still regularly encounter unrecoverable robot crashes. When using spqrl navigation this problem does not occur at all- what rate of unrecoverable crashes could be considered normal, and is there anything to be done about this?

**Comment by ccpjboss** [comment]
Thank you for starting an issue! What parameters did you change in the params file?

**Comment by jward0** [comment]
to costmap_common_params.yaml, I added
`plugins:`
`- {name: static_layer, type: "costmap_2d::StaticLayer"}`
`- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}`
`- {name: inflater_layer, type: "costmap_2d::InflationLayer"}`

from local_costmap_params.yaml, I removed
`   static_map: false`
from global_costmap_params.yaml, I removed
`   static_map: true`

**Comment by ccpjboss** [comment]
Hello again @jward0! 

The problem comes from the frame_id of the LaserScan sensor messages, which is `/robot_0/base_laser_link`. 

The problem is solved by using a custom version of stage_ros, that removes the initial '/'. We didn't realize that we were using this modified [stage_ros](https://github.com/imranlivt/stage_ros) package instead of the default one.

Please clone that repo into the same workspace of patrolling_sim and build the workspace again. We will soon modify the README file with installation instructions with this fix included.


Sorry for the inconvenience!

**Comment by jward0** [comment]
Thank you for the swift reply- I can confirm that this has fixed my problems. Thank you!
